version: '3'

services:
  konoha-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konoha-bot
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./session:/app/session
      - ./data:/app/data
      - ./temp:/app/temp
    environment:
      - TZ=Asia/Kolkata # Change to your timezone
      - NODE_ENV=production
    command: yarn start